default: &default
  adapter: postgresql
  pool: 5
  port: 5432
  username: <%= ENV['STACK_CLONE_DATABASE_USERNAME'] %>
  password: <%= ENV['STACK_CLONE_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: stack_clone_development

test:
  <<: *default
  database: stack_clone_test

production:
  <<: *default
  database: stack_clone_production
