# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 653512cbaac14d5b9421536ba3b44be5855c573d9bafc9ba075b78151d2734dc0e0c085f9993c05db30b08ba16a9291251757b320afaf4b3f64dddcac2cf3d48
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VK_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_APP_SECRET"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>

test:
  secret_key_base: 1636fa9504d63a77c1d03ce2d790413a8ca1a2d9199fa22017722270022c1cd2f6dc2fbeadc86f885fc6b44ea08ec6ae33acaa9a87490b2e299950b3aa4ab2fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_app_id: <%= ENV["TWITTER_APP_ID"] %>
  twitter_app_secret: <%= ENV["TWITTER_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VK_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_APP_SECRET"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>
